---
# tasks file for mysql
- name: Installation de mysql-server
  apt:
    pkg: mysql-server
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Installation de mariadb-server
  apt:
    pkg: mariadb-server
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: ansible_distribution == 'Debian'

- name: Démarrer MariaDB
  service:
    name: mysql
    state: started

- name: Installation des dépendances
  apt:
    pkg: ["php-mysql", "python3-pymysql"]
    update_cache: yes
    cache_valid_time: 86400
    state: present
#  notify:
#    - restart {{ wp_webserver }}

- name: Créer une base de données mysql
  mysql_db:
    name: "{{ magento_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Créer un utilisateur mysql
  mysql_user:
    name: "{{ magento_db_user }}"
    password: "{{ magento_db_password }}"
    priv: "*.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
