---
dependency:
  name: galaxy

driver:
  name: delegated
platforms:
  - name: test.datascientest.fr
   # groups:
   #   - test
   # hosts:
   #   - ansible_host: 15.236.40.42
    ssh_user: "datascientest"
    ansible_ssh_private_key_file: "~/.ssh/ansible-ec2-key.pem"

provisioner:
  name: ansible
#  hosts:
#    all:
#      hosts:
#        existing-instance:
 #         ansible_host: "15.236.40.42"
  inventory:
    links:
      hosts: ../../../../inventaire.yml
      group_vars: ../../../../group_vars
      host_vars: ../../../../host_vars
  playbooks:
    converge: ../../../../install_roles.yml

verifier:
  name: testinfra
