---
dependency:
  name: galaxy

driver:
  name: delegated
platforms:
  - name: test.datascientest.fr
    ssh_user: "datascientest"
    ansible_ssh_private_key_file: "~/.ssh/ansible-ec2-key.pem"

provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../../inventaire.yml
      group_vars: ../../../../group_vars
      host_vars: ../../../../host_vars
  playbooks:
    converge: ../../../../install_roles.yml

verifier:
  name: testinfra
