---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    pre_build_image: true 
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../../inventaire.yml
      group_vars: ../../../../group_vars
      host_vars: ../../../../host_vars
  playbooks:
    converge: ../../../../install_roles.yml
verifier:
  name: testinfra
