all:
  vars:
    ansible_user: datascientest
    #ansible_password: Datascientest2022
    ansible_become_pass: Datascientest2022
    ansible_ssh_private_key_file: ~/.ssh/ansible-ec2-key.pem

serveurdatabase:
  hosts:
    serveurdatabase1.datascientest.fr:
      ansible_host: 52.47.89.111
#  vars:
 #   tier: web

serveurweb:
  hosts:
    serveurweb1.datascientest.fr:
      ansible_host: 13.38.43.161
  #  tier: bd
