---
- name: Installation de  nginx
  apt:
    name: "nginx"
    state: present

- name: Démarrer le service php{{ php_version }}
  service:
    name: "php{{ php_version }}-fpm"
    state: started

- name: S'assurer qu'Apache2 est arrêté et désactivé
  ansible.builtin.systemd:
    name: apache2
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Magento | Nginx | Copier le fichier de configuration de l'hôte virtuel
  template:
    src: "magento_nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ magento_sitename }}"
    owner: root
    group: root
    mode: 0644
    force: yes
 # notify: Redémarrage Nginx

- name: Mettre à jour server_names_hash_bucket_size dans nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s#? *server_names_hash_bucket_size)'
    line: '        server_names_hash_bucket_size 128;'
    state: present
  notify: Redémarrage Nginx

- name: Mettre à jour nginx.conf pour pointer sur magento
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s*include\s+/etc/nginx/sites-enabled/\*;)'
    line: '        include /etc/nginx/sites-enabled/magento;'
    state: present

- name: Magento | Nginx | Fichier de configuration de l'hôte virtuel Symlink des sites disponibles aux sites activés
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ magento_sitename }}"
    dest: "/etc/nginx/sites-enabled/{{ magento_sitename }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: Redémarrage Nginx

- name: Ajouter www-data au groupe datascientest
  ansible.builtin.user:
    name: www-data
    groups: datascientest
    append: yes
  become: yes
  tags:
    - permissions
