---
#- name: Magento | Nginx | Déterminer l'emplacement du socket PHP FPM
#  shell: dpkg -l | grep php-fpm  | awk '{print $3}' | grep -o '[0-9]\.[0-9]' | head -n 1
#  register: "php_version"

- name: Démarrer le service php{{ php_version }}
  service:
    name: "php{{ php_version }}-fpm"
    state: started

- name: Démarrer le service nginx
  service:
    name: "nginx"
    state: started

- name: Magento | Nginx | Copier le fichier de configuration de l'hôte virtuel
  template:
    src: "magento_nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ magento_sitename }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: Redémarrage Nginx

- name: Augmenter la taille du server_names_hash_bucket_size pour Nginx
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s*server_names_hash_bucket_size\s+)(\d+);'
    line: 'server_names_hash_bucket_size 128;'
    create: yes
    backup: yes
  notify: Redémarrage Nginx

- name: Magento | Nginx | Fichier de configuration de l'hôte virtuel Symlink des sites disponibles aux sites activés
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ magento_sitename }}"
    dest: "/etc/nginx/sites-enabled/{{ magento_sitename }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: Redémarrage Nginx

- name: Ajouter www-data au groupe datascientest
  ansible.builtin.user:
    name: www-data
    groups: datascientest
    append: yes
  become: yes
  tags:
    - permissions
