---
# handlers file for magento
- name: Redémarrage Elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: Redémarrage Nginx
  service:
    name: nginx
    state: restarted
    enabled: true

- name: Supprimer l'ancien fichier local.xml.sample
  file:
    path: /var/www/magento/pub/errors/local.xml.sample
    state: absent

#- name: Restart PHP-FPM
#  service:
#    name: php-fpm
 #   state: restarted
